src/Entity/Wine.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use App\Traits\SoftDeleteable;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass="App\Repository\WineRepository")
 * @Vich\Uploadable()
 * * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Wine
{
    use SoftDeleteable;

    final public const COLOR = [
        'wine.color.red' => 'wine.color.red',
        'wine.color.white' => 'wine.color.white',
        'wine.color.rose' => 'wine.color.rose'
    ];

    final public const WINEGROWING = [
        'wine.growing.trad' => 'wine.growing.trad',
        'wine.growing.bio' => 'wine.growing.bio',
        'wine.growing.biodyn' => 'wine.growing.biodyn'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $filename = null;

    /**
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     *
     * )
     * @Vich\UploadableField(mapping="wine_image", fileNameProperty="filename")
     * )
     * @Vich\UploadableField(mapping="wine_image", fileNameProperty="filename")
     */
    private ?\Symfony\Component\HttpFoundation\File\File $imageFile = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $name = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description = null;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $year = null;


    /**
     * @ORM\Column(type="string", length=50, nullable=false)
     */
    private string $color = self::COLOR['wine.color.white'];

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $stock = null;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $price = null; //decimal ?

    /**
     * @ORM\Column(type="datetime")
     */
    private \DateTime|\DateTimeInterface $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Grape", inversedBy="wines")
     */
    private \Doctrine\Common\Collections\Collection|array $grapes;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private \DateTime|\DateTimeInterface|null $updated_at = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Appellation", inversedBy="wines",  cascade={"persist"})
     */
    private ?\App\Entity\Appellation $appellation = null;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=1, nullable=true)
     */
    private ?string $alcohol = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Container", inversedBy="wines")
     */
    private ?\App\Entity\Container $container = null;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Feature", inversedBy="wines")
     */
    private \Doctrine\Common\Collections\Collection|array $features;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Pairing", inversedBy="wines")
     */
    private \Doctrine\Common\Collections\Collection|array $pairings;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $location = null;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private ?string $winegrowing = self::WINEGROWING['wine.growing.trad'];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stock", mappedBy="wine", cascade={"remove", "persist"})
     */
    private \Doctrine\Common\Collections\Collection|array $stocks;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="wines")
     */
    private ?\App\Entity\User $user = null;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->grapes = new ArrayCollection();
        $this->features = new ArrayCollection();
        $this->pairings = new ArrayCollection();
        $this->stocks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->name);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }


    public function getColor(): ?string
    {
        return $this->color;
    }

    /**
     * @return $this
     */
    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }
    public function getWinegrowing(): ?string
    {
        return $this->winegrowing;
    }
    /**
     * @param string $winegrowing
     * @return $this
     */
    public function setWinegrowing(?string $winegrowing): self
    {
        $this->winegrowing = $winegrowing;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


    /**
     * @return Collection|Grape[]
     */
    public function getGrapes(): Collection
    {
        return $this->grapes;
    }

    public function addGrape(Grape $grape): self
    {
        if (!$this->grapes->contains($grape)) {
            $this->grapes[] = $grape;
            $grape->addWine($this);
        }

        return $this;
    }

    public function removeGrape(Grape $grape): self
    {
        if ($this->grapes->contains($grape)) {
            $this->grapes->removeElement($grape);
            $grape->removeWine($this);
        }

        return $this;
    }



    public function getAppellation(): ?Appellation
    {
        return $this->appellation;
    }

    public function setAppellation(?Appellation $appellation): self
    {
        $this->appellation = $appellation;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): Wine
    {
        $this->filename = $filename;
        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Wine
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


    public function getAlcohol(): ?string
    {
        return $this->alcohol;
    }

    public function setAlcohol(?string $alcohol): self
    {
        $this->alcohol = $alcohol;

        return $this;
    }

    public function getContainer(): ?Container
    {
        return $this->container;
    }

    public function setContainer(?Container $container): self
    {
        $this->container = $container;

        return $this;
    }


    /**
     * @return Collection|Feature[]
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features[] = $feature;
            $feature->addWine($this);
        }

        return $this;
    }

    public function removeFeature(Feature $feature): self
    {
        if ($this->features->contains($feature)) {
            $this->features->removeElement($feature);
            $feature->removeWine($this);
        }

        return $this;
    }

    /**
     * @return Collection|Pairing[]
     */
    public function getPairings(): Collection
    {
        return $this->pairings;
    }

    public function addPairing(Pairing $pairing): self
    {
        if (!$this->pairings->contains($pairing)) {
            $this->pairings[] = $pairing;
            $pairing->addWine($this);
        }

        return $this;
    }

    public function removePairing(Pairing $pairing): self
    {
        if ($this->pairings->contains($pairing)) {
            $this->pairings->removeElement($pairing);
            $pairing->removeWine($this);
        }

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {

src/Controller/WineController.php
<?php
namespace App\Controller;
use App\Entity\Appellation;
use App\Entity\Wine;
use App\Entity\WineSearch;
use App\Form\WineSearchType;
use App\Repository\AppellationRepository;
use App\Repository\WineSearchRepository;
use App\Repository\RegionRepository;
use App\Repository\WineRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
// Include Dompdf required namespaces
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Component\Serializer\Serializer;
use Twig\Environment;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
class WineController extends AbstractController
{
    public function __construct(private readonly WineRepository $repository, private readonly EntityManagerInterface $em, private readonly Environment $twig, private readonly Pdf $pdf)
    {
    }

    /**
     * @Route("/wines", name="wine.index")
     */
    public function index(PaginatorInterface $paginator, Request $request, WineSearchRepository $wineSearchRepository): Response
    {
        $search = $wineSearchRepository->findOneByUser($this->getUser());
        if (!$search)
        {
            $search = new WineSearch();
            $search->setUser($this->getUser());
        }

        if ($request->getMethod() == 'POST')
        {
            $search->getGrapes()->clear();
            $search->getFeatures()->clear();
            $search->getPairings()->clear();
        }

        $form = $this->createForm(WineSearchType::class, $search, [
            "action" => $this->generateUrl('wine.index'),
            "method" => "POST",
            "attr" => [
                "id" > "wineSearch"
            ]
        ])
            ->handleRequest($request);

        if ($form->isSubmitted())
        {
            $this->em->persist($search);
            $this->em->flush();
        }

        $wines = $paginator->paginate(
            $this->repository->findAllVisibleQuery($this->getUser(), $search),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('wine/index.html.twig', [
            'current_menu' => 'wines',
            'wines' => $wines,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/wines/{slug}-{id}", name="wine.show", requirements={"slug": "[a-z0-9\-]*" })
     *
     *
     * @ParamConverter(
     *     "wine",
     *     class="App\Entity\Wine",
     *     options={
     *         "repository_method" = "findOneById",
     *         "mapping": {"id": "id"},
     *         "map_method_signature" = true
     *     }
     * )
     */
    public function show(Wine $wine, string $slug): Response
    {
        if ($wine->getSlug() !== $slug) {
            return $this->redirectToRoute('wine.show', [
                'id' => $wine->getId(),
                'slug' => $wine->getSlug()
            ], 301);
        }
        return $this->render('wine/show.html.twig', [
            'wine' => $wine,
            'current_menu' => 'wines'
        ]);
    }
    /**
     * @Route("/listp", name="wine.list", methods={"GET"})
     */
    public function listp(RegionRepository $regionRepository): Response
    {
        $regions = $regionRepository->findBy([], ["name" => "ASC"]);
        $totalBottles = 0;
        $totalPrices = 0;
        foreach($regions as $region)
        {
            $totalBottles += $region->getTotalBottles();
            $totalPrices += $region->getTotalPrices(true);
        }
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Times');
//        $pdfOptions->set('isRemoteEnabled', true);
//        $pdfOptions->set('isHtml5ParserEnabled', true);
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        $regions = $regionRepository->findBy([], ["name" => "ASC"]);
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('wine/snappy.html.twig',[
            'regions' => $regions,
            'totalBottles' => $totalBottles,
            'totalPrices' => $totalPrices
        ]);
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');
        // Render the HTML as PDF
        $dompdf->render();
        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);
    }
    /**
     * @Route("/pdf", name="pdf")
     * @return Response
     */
    public function pdf(RegionRepository $regionRepository)
    {
        $regions = $regionRepository->findBy([], ["name" => "ASC"]);
        $totalBottles = 0;
        $totalPrices = 0;
        foreach($regions as $region)
        {
            $totalBottles += $region->getTotalBottles();
            $totalPrices += $region->getTotalPrices(true);
        }
        $html = $this->renderView('wine/snappy.html.twig', [
            'regions' => $regions,
            'totalBottles' => $totalBottles,
            'totalPrices' => $totalPrices
        ]);
        return new PdfResponse(
            $this->pdf->getOutputFromHtml($html),
            'liste.pdf',
            'application/pdf',
            'inline'
        );
    }
    /**
     * @Route("/stat", name="stat")
     * @return type
     */
    public function statRegion()
    {
        $wine = $this->getDoctrine()->getRepository(Wine::class)->findAll();
        $nbregion = 0;
        foreach ($wine as $wine) {
            $nbregion += $wine->getTotalBottles();
        }
        $pieChart = new PieChart();
        $pieChart->getData()->setArrayToDataTable(
            [['Region', 'Number'],
                ['Alsace',    $nbregion ],
                ['Beaujolais',     0],
                ['Bordeaux',      15],
                ['Bourgogne',  25],
                ['Champagne', 3],
                ['Jura-Savoie',    18],
                ['Languedox-Roussillon',    0],
                ['Loire',    1],
                ['Provence-Corse',    0],
                ['Rhône',    5],
                ['Sud-Ouest',    1],
            ]
        );
        $pieChart->getOptions()->setTitle('Vins par région');
        $pieChart->getOptions()->setHeight(500);
        $pieChart->getOptions()->setWidth(900);
        $pieChart->getOptions()->getTitleTextStyle()->setBold(true);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#009900');
        $pieChart->getOptions()->getTitleTextStyle()->setItalic(true);
        $pieChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(20);
        return $this->render('wine/stat.html.twig', ['piechart' => $pieChart]);
    }
}

templates/wine/_filter.html.twig
{{ form_start(form) }}
<div class="form-row align-items-end">
    <div class="col">
        {{ form_row(form.name) }}
    </div>
    <div class="col">
        {{ form_row(form.color) }}
    </div>
    <div class="col">
            {{ form_row(form.appellation) }}
    </div>
    <div class="col">
        {{ form_row(form.minYear) }}
    </div>
</div>
<div class="form-row align-items-end">
    <div class="col">
        {{ form_row(form.grapes) }}
    </div>
    <div class="col">
        {{ form_row(form.features) }}
    </div>
    <div class="col">
        {{ form_row(form.pairings) }}
    </div>

    <div class="col">
        {{ form_row(form.maxPrice) }}
    </div>
</div>

<div class="form-row align-items-end">
    <div class="col">
        <div class="form-groupe">
            <button class="btn btn-primary">Rechercher</button>
        </div>
    </div>
    <a href="{{ path('wine.list') }}" class="btn btn-primary" target="_blank">Imprimer tous les vins</a>
</div>

{{ form_end(form) }}

templates/wine/_listp.html.twig
<table class="table">
    <thead>
    <tr>
        <th>Nom</th>
        <th style="text-align: center">Millésime</th>
        <th style="text-align: center">Appellation</th>
        <th style="text-align: center">Couleur</th>
        <th>Cépages</th>
        <th style="text-align: center">Qté</th>
        <th style="text-align: center">P.U.</th>
    </tr>
    </thead>
    <tbody>

    {#    {% for appellation in region.appellations %}#}
    {% for wine in region.wines %}
        <tr>
            <td>{{ wine.name }}</td>
            <td style="text-align: center">{{ wine.year }}</td>
            <td>{{ wine.appellation.name }}</td>
{#            <td style="text-align: center"><img src="{{ './images/wines/' ~ wine.color ~ '.jpg' }}"#}
{#                                                alt="card-img-top"#}
{#                                                style=" height: 35px; width: auto;"></td>#}
            <td>{{ wine.color|trans }}</td>
            <td>
                {% for grape in wine.grapes %}
                    {{ grape.name }}
                {% endfor %}
            </td>
            <td style="text-align: center">{{ wine.nbbottle}}</td>
            <td style="text-align: center">{{ wine.price|price }}</td>
        </tr>
    {% endfor %}
    {#    {% endfor %}#}
    </tbody>
</table>

templates/wine/_sidebar_filter.html.twig
{{ form_start(form) }}
<div class="col-sm-10">
    <li>Nom</li>
    {{ form_widget(form.name) }}
</div>
<div class="col-sm-10">
    <li>Couleur</li>
    {{ form_widget(form.color) }}
</div>
<div class="col-sm-10">
    <li>Appellation</li>
    {{ form_widget(form.appellation) }}
</div>
<div class="col-sm-10">
    <li>Viticulture</li>
    {{ form_widget(form.winegrowing) }}
</div>
<hr>
<div class="col-sm-10">
    <li>Cépages</li>
    {{ form_widget(form.grapes) }}
</div>

<div class="col-sm-10">
    <li>Caractéristiques</li>
    {{ form_widget(form.features) }}
</div>
<div class="col-sm-10">
    <li>Associations</li>
    {{ form_widget(form.pairings) }}
</div>
<hr>
<div class="col-sm-10">
        {{ form_row(form.minYear) }}
</div>
<div class="col-sm-10">
    {{ form_row(form.maxPrice) }}
</div>
<div class="col-sm-10">
    {{ form_row(form.isStock) }}
</div>
{{ form_rest(form) }}

<div class="col">
    <div class="form-groupe">
        <button class="btn btn-primary">Rechercher</button>
    </div>
</div>
{{ form_end(form) }}
</ul>

templates/wine/_wine.html.twig
<div class="card mb-4">
    {% if wine.filename %}
        <img src="{{ vich_uploader_asset(wine, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top"
             >
    {% else %}
        <img src="{{ '/images/wines/empty.jpg' }}" alt="card-img-top"
             style="width: 100%; height: auto">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('wine.show', {slug: wine.slug, id: wine.id}) }}">
                {{ wine.name }}
            </a>
        </h5>
      <p class="card-text">{{ wine.appellation.name }} {{ wine.year }}</p>

        <a href="{{ path('stock.movement',{id: wine.id}) }}" class="btn btn-light float-right" >+ / -</a>
        <img src="{{ './images/wines/' ~ wine.color ~ '.jpg' }}" alt="card-img-top"
             style="width: 10%; height: auto">

        <div class="text-primary" style="font-size:2rem; font-weight: bold;">
            {{ wine.stock }}
            {#  {{ wine.formattedPrice }} €#}
        </div>
    </div>
</div>

templates/wine/listp.html.twig
{% block body %}
    <h1 align="center">Liste des vins</h1>

    <h2>France</h2>

    {% set appellation = 'Alsace' %}
    <h3>Alsace</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Beaujolais' %}
    <h3>Beaujolais</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Bourgogne' %}
    <h3>Bourgogne</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Bordeaux' %}
    <h3>Bordeaux</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Champagne' %}
    <h3>Champagne</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Jura-Savoie' %}
    <h3>Jura-Savoie</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Languedoc-Roussillon' %}
    <h3>Languedoc-Roussillon</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Loire' %}
    <h3>Loire</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Provence-Corse' %}
    <h3>Provence-Corse</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Rhône' %}
    <h3>Rhône</h3>
    {% include 'wine/_listp.html.twig' %}

    {% set appellation = 'Sud-Ouest' %}
    <h3>Sud-Ouest</h3>
    {% include 'wine/_listp.html.twig' %}



    <h2>Vins hors de France</h2>
    <table class="table">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Millésime</th>
            <th>Appellation</th>
            <th>Couleur</th>
        </tr>
        </thead>
        <tbody>
        {% for wine in wines|sort((a, b) => a.name <=> b.name) %}
            {% if wine.appellation.region.country != 1 %}
                <tr>
                    <td>{{ wine.name }}</td>
                    <td>{{ wine.year }}</td>
                    <td>{{ wine.appellation.name }}</td>
                    <td><img src="{{ './images/wines/' ~ wine.color ~ '.jpg' }}" alt="card-img-top"
                             style=" height: 35px; width: auto"></td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/wine/show.html.twig
{% extends 'base.html.twig' %}

{% block title wine.name %}


{% block body %}
<div id="content">

    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    {% if wine.filename %}
                        <img src="{{ vich_uploader_asset(wine, 'imageFile') | imagine_filter('thumb') }}"
                             alt="card-img-top" style="width: 100%; height: auto">
                    {% else %}
                        <img src="{{ '/images/wines/empty.jpg' | imagine_filter('medium') }}" alt="card-img-top"
                             style="width: 100%; height: auto">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1>{{ wine.name }} {{ wine.year }}</h1>
                    <h2>{{ wine.appellation.name }}</h2>
                    {# <div class="text-primary" style="font-size: 4rem; font-weight:bold;" >{{ wine.formattedPrice }}</div> #}
                    {# <a href="#" class="btn btn-primary">Contacter???</a>} #}
                </div>
            </div>

        </div>
    </div>
    <div class="container mt-8">

        <p>
            {{ wine.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-6">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">

                    <tr>
                        <td>Appellation</td>
                        <td>{{ wine.appellation.name }} ({{ wine.appellation.region.name }})</td>
                    </tr>
                    <tr>
                        <td>Couleur</td>
                        <td>{{ wine.color|trans|capitalize }}</td>
                    </tr>
                    <tr>
                        <td>Viticulture</td>
                        <td>{{ wine.winegrowing|default|trans }}</td>
                    </tr>
                    <tr>
                        <td>Alcool</td>
                        <td> {{ wine.alcohol|alcohol }} </td>
                    </tr>
                    <tr>
                        <td>Contenance</td>
                        <td>{{ wine.container.name }}
                            ({{ wine.container.capacity|capacity }} {{ wine.container.unit }})
                        </td>
                    </tr>
                    <tr>
                        <td>Stock</td>
                        <td>{{ wine.stock }}</td>
                    </tr>
                    <tr>
                        <td>Emplacement</td>
                        <td>{{ wine.location }}</td>
                    </tr>
                    <tr>
                        <td>Producteur (pas encore implémenté)</td>
                        <td></td>
                    </tr>
                </table>
            </div>

            <div class="col-md-6">
                <h2>Cépages</h2>
                <ul class="list-group">
                    {% for grape in wine.grapes %}
                        <li class="list-group-item">{{ grape.name }}</li>
                    {% endfor %}
                </ul>
                <h2>Caractéristiques</h2>
                <ul class="list-group">
                    {% for feature in wine.features %}
                        <li class="list-group-item">{{ feature.name }}</li>
                    {% endfor %}
                </ul>

                <h2>Associations</h2>
                <ul class="list-group">
                    {% for pairing in wine.pairings %}
                        <li class="list-group-item">{{ pairing.name }}</li>
                    {% endfor %}
                </ul>





            </div>


        </div>
        <h2>Historique du stock</h2>
        <a href="{{ path('stock.movement',{id: wine.id}) }}" class="btn btn-light float-right" >+ / -</a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Nombre</th>
                <th>In / Out</th>
                <th>Commentaire</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for movement in wine.stocks %}
                <tr>
                    <td>{{ movement.id }} </td>
                    <td>{{ movement.createdAt|date('d-m-Y') }} </td>
                    <td> {{ movement.quantity }} </td>
                    <td>  {{ movement.movement|trans }}</td>
                    <td> {{ movement.comment }}</td>
                    <td>
                        <a href="{{ path ('movement.edit', {id: movement.id}) }}" class="btn btn-secondary">Editer</a>
                        <form method="post" action="{{ path('movement.delete', {id: movement.id}) }}"
                              style="display: inline-block" onsubmit="return confirm('Êtes-vous certain?')">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movement.id) }}">
                            <button class="btn btn-danger">Supprimer</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}